import matplotlib
matplotlib.use('Agg')
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Load the dataset generated by C++
df = pd.read_csv('landing_results.csv')

plt.figure(figsize=(10, 8))

# Plot True Landing Points
plt.scatter(df['true_x'], df['true_y'], c='green', label='True Landing Point (MuJoCo)', marker='o', s=100, alpha=0.6)

# Plot EKF Predicted Landing Points
plt.scatter(df['pred_x'], df['pred_y'], c='red', label='EKF Predicted Landing', marker='x', s=100)

# Draw connecting lines to visualize the error margin
for i in range(len(df)):
    plt.plot([df['true_x'][i], df['pred_x'][i]], 
             [df['true_y'][i], df['pred_y'][i]], 'k--', alpha=0.3)

# Draw a target/origin reference
plt.scatter(0, 0, c='black', marker='+', s=200, label='Launch Point')

plt.title('EKF Ball Landing Prediction Validation (50 Throws)')
plt.xlabel('X Position (meters)')
plt.ylabel('Y Position (meters)')
plt.legend()
plt.grid(True)
plt.axis('equal')

# Calculate and display the mean error
mean_error = df['error'].mean()
plt.text(0.05, 0.95, f'Mean Prediction Error: {mean_error:.4f} m', 
         transform=plt.gca().transAxes, fontsize=12,
         verticalalignment='top', bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))

plt.savefig('landing_results.png')